### ISSUE TITLE
Spatial regularizer

### ISSUE THREAD

**Issue by vadimkantorov** [hbilen/WSDDN#1]
Hi Hakan,

Thanks for putting the code online, it's really a nice and concise code base! I've got two questions concerning the spatial regularizer:

1) As far as I can see in https://github.com/hbilen/WSDDN/blob/master/layers/LossTopBoxSmoothProb.m#L69,
you are also putting the `probs`  values under the square opposite to the formulation in subsection 3.4 of the paper. Also the gradient computation in https://github.com/hbilen/WSDDN/blob/master/layers/LossTopBoxSmoothProb.m#L85 doesn't square the `probs` value that doesn't correspond to the forward pass code. Am I missing something or is it a bug?

2) Do I understand correctly that you differentiate the regularizer only wrt fc7 outputs?

Thanks in advance!

**Comment by hbilen** [comment]
I have updated the equation in the paper. Thanks to Vadim Kantorov and Siniša Šegvić. Now the implementation should be consistent with the paper.

**Comment by senthilps8** [comment]
Sorry for reviving this. Can you point me to the new version of the paper?
Correct me if I'm wrong. From what I understand, [this](https://www.robots.ox.ac.uk/~vgg/publications/2016/Bilen16/bilen16.pdf) and [this](https://arxiv.org/pdf/1511.02853v3.pdf) version still have the issue that @vadimkantorov  pointed out.

**Comment by hbilen** [comment]
Thanks Senthil, the paper was somehow not updated in the vgg website. I 
think it should be the right version now. Here is the link:

http://www.robots.ox.ac.uk/~vgg/publications/2016/Bilen16/bilen16.pdf

**Comment by vadimkantorov** [comment]
Still, from what I can understand, the backward pass [doesn't](https://github.com/hbilen/WSDDN/blob/master/layers/LossTopBoxSmoothProb.m#L85) square the probs, while the forward pass [does](https://github.com/hbilen/WSDDN/blob/master/layers/LossTopBoxSmoothProb.m#L69).

Since the differentiation is done only wrt fc7, probs should also be squared in the backward pass, right?

**Comment by vadimkantorov** [comment]
Still, from what I can see, the forward pass [squares](https://github.com/hbilen/WSDDN/blob/master/layers/LossTopBoxSmoothProb.m#L69) the `probs` while the backward [doesn't](https://github.com/hbilen/WSDDN/blob/master/layers/LossTopBoxSmoothProb.m#L85). Shouldn't they be consistent on this?

**Comment by senthilps8** [comment]
Yes, I think the backward prop uses the previous formulation of the loss #4

**Comment by hbilen** [comment]
Thanks, you are right. I guess if we square probs term, it is gonna be correct, isn't it? This might require some change in the scaling term. I will try to run an experiment with that.

**Comment by vadimkantorov** [comment]
Yep, seems squaring probs in backward pass would make it correct

**Comment by css1995** [comment]
@vadimkantorov  Sorry, could you show me the code after  squaring probs in backward pass?
