### ISSUE TITLE
When run cnn_wsddn_demo meet the problem

### ISSUE THREAD

**Issue by yanxp** [hbilen/WSDDN#10]
Error using vl_nnconv
An input is not a numeric array (or GPU support not compiled).

Error in dagnn.Conv/forward (line 11)
      outputs{1} = vl_nnconv(...

Error in dagnn.Layer/forwardAdvanced (line 85)
      outputs = obj.forward(inputs, {net.params(par).value}) ;

Error in dagnn.DagNN/eval (line 88)
  obj.layers(l).block.forwardAdvanced(obj.layers(l)) ;

Error in cnn_wsddn_demo (line 98)
      net.eval(inputs) ;

**Comment by hbilen** [comment]
The problem might be that you didn't compile matconvnet.
