### ISSUE TITLE
There are seem to be a bug in layers/LossTopBoxSmoothProb.m

### ISSUE THREAD

**Issue by chengmengli06** [hbilen/WSDDN#11]
o = find((inter ./ (gtArea + area - inter))>obj.minOverlap);
inter gtArea, area and inter  are actually of uint16, so o could only be 0 or 1(when actual value > 0.5), so an setting of minOverlap = 0.6 is useless.

**w = max(0.0, xx2-xx1+1);
 h = max(0.0, yy2-yy1+1);
w and h are still uint16;**

**And (gtArea + area - inter) could overflow**

I use matlab   ##R2014a

**Comment by hbilen** [comment]
Thanks, it should be fixed now.
