### ISSUE TITLE
Code Error!!! 

### ISSUE THREAD

**Issue by ChrisAllenMing** [hbilen/WSDDN#13]
When we train your model WSDDN, we met a problem on reshaping the matrix of confidence on proposals (i.e. imdb.images.boxScores{batch}). The error logs are listed as belows.

`Error using reshape
Size arguments must be integer scalars.

Error in cnn_wsddn_train>getBatch (line 204)
  boxScore = reshape(imdb.images.boxScores{batch},[1 1 1
  numel(imdb.images.boxScores{batch})]);`

**Comment by ChrisAllenMing** [comment]
Sorry, we change the batch size from 1 to 4 so that the reshape function get confused on operating on the cell matrix.

**Comment by css1995** [comment]
Hello, I met this problem, too.  This code works only if the batch size is 1. Have you got the solution  to train the network in a bigger batch size?
