### ISSUE TITLE
It seems that no content exists in vl_nnspp.m

### ISSUE THREAD

**Issue by ChrisAllenMing** [hbilen/WSDDN#14]
In training process, we found that 'vl_nnspp'  function is called but there is no content in WSDDN/layers/matlab/vl_nnspp.m. Maybe we can compile vl_nnspp.cu into a mex file. Is it right and how can we do that? Thanks for your future solution.

**Comment by hbilen** [comment]
Hi, I have made quite some changes. Now it does not require any extra compilation. You just need to install matconvnet and use vl_contrib to install the package.
