### ISSUE TITLE
compile failed

### ISSUE THREAD

**Issue by tztztztztz** [hbilen/WSDDN#15]
matlab version: 2015b
GPU: GTX 1080TI
CUDA: 7.0
cudnn: 4.0

`nvcc fatal   : Unsupported gpu architecture 'compute_61'`

it seems like cuda7.0 doesn't support my GPU

==============================================
however, when I change to matlab 2017a, cuda 8.0
it turns out that there is some function whose name is same as cuda toolkit's funtion.
Error using mex
`/home/tz/projects/WSDDN/matconvnet/matlab/src/bits/impl/pooling_gpu.cu(163): error: function "atomicAdd(double *, double)"
has already been defined
1 error detected in the compilation of "/tmp/tmpxft_00007b3f_00000000-7_pooling_gpu.cpp1.ii".`
and it failed, too.

is there some solutions?

**Comment by hbilen** [comment]
Hi, I have made quite some changes. You can now just install matconvnet and use vl_contrib to install WSDDN.
