### ISSUE TITLE
x1 and y1 seem to be switched

### ISSUE THREAD

**Issue by vadimkantorov** [hbilen/WSDDN#2]
Hi,

In my understanding, you store boxes in format [y1 x1 y2 x2], yet at https://github.com/hbilen/WSDDN/blob/master/layers/LossTopBoxSmoothProb.m#L43 you are refering to them as [x1 y1 x2 y2]. As far as I get, this minor mis-reference is not a problem because the IOU formula is symmetric wrt to coordinates.

Am I right?

**Comment by ZiangYan** [comment]
I agree with you. In my understanding, Edgebox proposals are stored in format [y1 x1 y2 x2], 1-based index. This protocol is widely used in many open source computer vision projects, e.g., fast-rcnn.

**Comment by hbilen** [comment]
Yes indeed. It hasn't any influence on the result but it might be confusing.
