### ISSUE TITLE
Errors in 'cnn_wsddn_train.m' need to be fixed.

### ISSUE THREAD

**Issue by Phoenix1327** [hbilen/WSDDN#5]
**line 161~162** in 'cnn_wsddn_train.m'

inputs = {'input', im, 'label', labels, 'rois', rois, 'ids', batch, ...
    'boxes', imdb.images.boxes{batch}} ;

When we use **LossSmooth**, that is, set opts.addLossSmooth = 1 in line 23, there is no problem;
But if we **do not** use LossSmooth, line 161~162 should be changed to:

inputs = {'input', im, 'label', labels, 'rois', rois, 'ids', batch} ;

Since we do not need the variable 'boxes' in the training net without LossSmooth.****

**Comment by hbilen** [comment]
Thank you, that should be fixed now.
