### ISSUE TITLE
cannot find -lstdc++

### ISSUE THREAD

**Issue by ghost** [hbilen/WSDDN#6]
Hi, I have a question with compiling the toolbox. I hit this error when I run vl_wsddn_compilenn in MATLAB(I also couldn't find cnn_wsddn_compilenn). 

#warning "SSSE3 instruction set not enabled. Using slower image conversion routines."
  ^
    Warning: No source files in argument list. Assuming C source
             code for linking purposes. To override this
             assumption use '-fortran' or '-cxx'.
/usr/bin/ld: cannot find -lstdc++
collect2: error: ld returned 1 exit status
    mex: link of ' "/home/hanwang/WSDDN/matconvnet/matlab/mex/vl_nnconv.mexa64"' failed.
    Unable to complete successfully.
    Error in vl_wsddn_compilenn>mex_link (line 506)
   mex(mopts{:}) ;
    Error in vl_wsddn_c ompilenn (line 458)
  mex_link(opts, objs, mex_dir, flags.link) ;
 

#

Any idea how do i fix this? Thanks.

**Comment by hbilen** [comment]
Sorry I have just seen this. I believe this should be a matconvnet problem. Please have a look at https://groups.google.com/forum/#!forum/matconvnet
