### ISSUE TITLE
Errors when run cnn_wsddn_demo.m

### ISSUE THREAD

**Issue by anthony123** [hbilen/WSDDN#8]
the error messages is as followings:

>尝试将 SCRIPT vl_nnspp 作为函数执行:
/media/liuwq/7A0EA5000EA4B713/WSDDN/layers/matlab/vl_nnspp.m
出错 SPP/forward (line 97)
      outputs{1} = vl_nnspp(inputs{1}, self.levels, rois, ...
 出错 dagnn.Layer/forwardAdvanced (line 85)
      outputs = obj.forward(inputs, {net.params(par).value}) ;
 出错 dagnn.DagNN/eval (line 88)
  obj.layers(l).block.forwardAdvanced(obj.layers(l)) ;
 出错 cnn_wsddn_demo (line 100)
      net.eval(inputs) ;

the scripts are:

>  opts.modelPath= 'models/vggf-edgeboxes-boxsc-spatreg.mat' ;
 opts.imdbPath = 'exp/imdb.mat' ;
opts.train.gpus = 0;
 cnn_wsddn_demo(opts);

So what's the problem?

**Comment by hbilen** [comment]
You need to compile the code with vl_wsddn_compilenn.m instead of vl_compilenn.m and set opts.train.gpus = [] or opts.train.gpus =1 if you have a gpu

**Comment by anthony123** [comment]
Thank you. It solved my problem

**Comment by alexshaodong** [comment]
> You need to compile the code with vl_wsddn_compilenn.m instead of vl_compilenn.m and set opts.train.gpus = [] or opts.train.gpus =1 if you have a gpu

Hello! If I want to train with my own data, how to generate edgeboxes mat files, similar to EdgeBoxes VOC2007trainval. mat and EdgeBoxes VOC2007test. mat files.

**Comment by alexshaodong** [comment]
> Thank you. It solved my problem

Hello! If I want to train with my own data, how to generate edgeboxes mat files, similar to EdgeBoxes VOC2007trainval. mat and EdgeBoxes VOC2007test. mat files.
