### ISSUE TITLE
When run cnn_wsdnn_train.m meet the problem

### ISSUE THREAD

**Issue by yanxp** [hbilen/WSDDN#9]
Error using cellfun
Input #2 expected to be a cell array, was struct instead.

Error in prepare_wsddn (line 13)
relu6p = find(cellfun(@(a) strcmp(a.name, 'relu6'), net.layers)==1);

Error in cnn_wsddn_train (line 60)
net = prepare_wsddn(net,nopts);

**Comment by drcege** [comment]
Same problem.

**Comment by drcege** [comment]
@yanxp  I know the reason.  In the training phase, you should use `imagenet-vgg-f.mat` instead of `vggf-edgeboxes-boxsc-spatreg.mat`.  After loading imagenet-vgg-f.mat, its layers field is a 1x21 cell array.

**Comment by alexshaodong** [comment]
> Error using cellfun
> Input #2 expected to be a cell array, was struct instead.
> 
> Error in prepare_wsddn (line 13)
> relu6p = find(cellfun(@(a) strcmp(a.name, 'relu6'), net.layers)==1);
> 
> Error in cnn_wsddn_train (line 60)
> net = prepare_wsddn(net,nopts);

Hello! If I want to train with my own data, how to generate edgeboxes mat files, similar to EdgeBoxes VOC2007trainval. mat and EdgeBoxes VOC2007test. mat files.

**Comment by alexshaodong** [comment]
> @yanxp I know the reason. In the training phase, you should use `imagenet-vgg-f.mat` instead of `vggf-edgeboxes-boxsc-spatreg.mat`. After loading imagenet-vgg-f.mat, its layers field is a 1x21 cell array.

Hello! If I want to train with my own data, how to generate edgeboxes mat files, similar to EdgeBoxes VOC2007trainval. mat and EdgeBoxes VOC2007test. mat files.
